# -*- coding: utf-8 -*-
"""python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s-kNOE3BKPL3EpIm28sdv-6fXiGEdchz
"""

# Importamos tabulate para pode crear la vista de la tabla
from tabulate import tabulate

# Cargamos en una variable de tipo arreglo las 5 nota de los 10 estudiantes
data = [
    [13,16,15,20,11],
    [15,18,15,20,11],
    [15,11,12,20,11],
    [15,16,13,11,11],
    [15,11,16,20,11],
    [15,11,16,20,14],
    [15,16,17,20,10],
    [15,11,15,20,11],
    [15,14,11,20,11],
    [15,16,11,20,11],
]

# creamos una tabla de tipo arreglo para almacenar el registro el numero de estudiante, las notas y el promedio
tabla = []
for i in range(len(data)): #for para recorrer estudiantes
  tabla.append([])  # agregamos un registro al arreglo
  tabla[i].append("Estudiante "+ str(i+1)) # definimos el numero de estudiante
  sumNota=0 #iniciamos la variable en cero para almacenar las notas de los examenes 
  for j in range(len(data[i])): #for para recorrer notas
    nota = data[i][j] # asiganos la nota de examen
    tabla[i].append(nota) # agregamos a la tabla la nota por cada examen
    sumNota += nota # suamnos todoas las notas de los examen por cada registro de estudiantes
  tabla[i].append(sumNota/len(data[i])) # realizamos al la operacion para el promedio y agregamos a la tabla
  

# agregamos un registro al arreglo
tabla.append([])
tabla[len(data)].append("Resumen")
for j in range(len(tabla[1])): # recorremos la columna de la tabla
  if j == 0 : continue # saltamos el primer registro 
  sumColumna = 0 #iniciamos la suma de columnas en 0
  for i in range(len(tabla)-1): # recorremos las filas de la tabla
    sumColumna += tabla[i][j]  # sumamos las columnas de cada examen y el promedio para el resumen
  tabla[len(tabla)-1].append(sumColumna/(len(tabla)-1)) # agregamos el promedio del resumen de cada columna


# creamos una variable tipo arreglo para el encabezado de la tabla
head = ["Estudiante","Examen 1", "Examen 2", "Examen 3", "Examen 4", "Examen 5", "Promedio"]  
# imprimos la tabla con los registros y el encabezado 
print(tabulate(tabla, headers=head, tablefmt="grid"))



